apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    docker.io/hostpath: /var/lib/k8s-pvs/test-pvc-new/pvc-3461f325-527e-421b-9c01-acf32b3398ad
    pv.kubernetes.io/provisioned-by: docker.io/hostpath
  creationTimestamp: "2024-05-01T13:48:34Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-3461f325-527e-421b-9c01-acf32b3398ad
  resourceVersion: "41232"
  uid: a6130ca8-9696-423d-a841-0f7780b46e14
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-pvc-new
    namespace: volumes
    resourceVersion: "41227"
    uid: 3461f325-527e-421b-9c01-acf32b3398ad
  hostPath:
    path: /var/lib/k8s-pvs/test-pvc-new/pvc-3461f325-527e-421b-9c01-acf32b3398ad
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-05-01T13:48:34Z"
  phase: Bound
