apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: test-pvc
  namespace: volumes
spec: 
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  storageClassName: hostpath
