apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web01
  namespace: volumes
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web01
  serviceName: nginx
  template:
    metadata:
      labels:
        app: web01
    spec:
      containers:
      - image: httpd:alpine
        name: web01
        ports:
        - containerPort: 80
          name: web01
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 4
  collisionCount: 0
  currentReplicas: 4
  currentRevision: web01-796f7bb4d5
  observedGeneration: 2
  readyReplicas: 4
  replicas: 4
  updateRevision: web01-796f7bb4d5
  updatedReplicas: 4

---

apiVersion: v1
kind: Service
metadata:
  name: web01-service
  namespace: volumes
  labels:
    app: web01
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: web01

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web01
  namespace: volumes
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: web01
  targetCPUUtilizationPercentage: 75
status:
  currentReplicas: 0
  desiredReplicas: 0
